// Data 23 tema untuk gallery
// icon = FontAwesome FREE solid class (pasti ada di kit free 6.x)
const THEMES = [
  // 10 Coffee (dark pekat)
  {slug:"cinnamon-latte", name:"Cinnamon Latte", icon:"fa-mug-saucer", group:"coffee", desc:"Kayu manis hangat", tagline_id:"Hangatnya bikin lupa deadline.", tagline_en:"The warmth makes you forget deadlines.", vars:["--caramel","--sunset","--espresso","--card","--cream","--border"]},
  {slug:"mocha-night", name:"Mocha Night", icon:"fa-mug-hot", group:"coffee", desc:"Mocha pekat, kontras tinggi", tagline_id:"Buat yang begadah tapi stylish.", tagline_en:"All-nighters, but make it stylish.", vars:["--caramel","--sunset","--espresso","--card","--cream","--border"]},
  {slug:"caramel-macchiato", name:"Caramel Macchiato", icon:"fa-cookie", group:"coffee", desc:"Karamel manis, cerah", tagline_id:"Manisnya pas, nggak bikin enek.", tagline_en:"Sweet spot, no overdose.", vars:["--caramel","--sunset","--espresso","--card","--cream","--border"]},
  {slug:"sunset-ember", name:"Sunset Ember", icon:"fa-fire", group:"coffee", desc:"Bara senja menyala", tagline_id:"Api semangat di ujung jari.", tagline_en:"Fire of passion at your fingertips.", vars:["--caramel","--sunset","--espresso","--card","--cream","--border"]},
  {slug:"hazelnut-cream", name:"Hazelnut Cream", icon:"fa-seedling", group:"coffee", desc:"Krim hazelnut kalem", tagline_id:"Kalem tapi ngena, kayak mantan baik.", tagline_en:"Calm but hits different, like a good ex.", vars:["--caramel","--sunset","--espresso","--card","--cream","--border"]},
  {slug:"espresso-shot", name:"Espresso Shot", icon:"fa-bolt", group:"coffee", desc:"Espresso bold, berani", tagline_id:"Satu shot, langsung ngegas.", tagline_en:"One shot, full throttle.", vars:["--caramel","--sunset","--espresso","--card","--cream","--border"]},
  {slug:"vanilla-bean", name:"Vanilla Bean", icon:"fa-leaf", group:"coffee", desc:"Vanilla creamy fresh", tagline_id:"Clean girl aesthetic, buat kode.", tagline_en:"Clean aesthetic, for clean code.", vars:["--caramel","--sunset","--espresso","--card","--cream","--border"]},
  {slug:"chocolate-truffle", name:"Chocolate Truffle", icon:"fa-gem", group:"coffee", desc:"Cokelat truffle mewah", tagline_id:"Mewah tapi nggak bikin miskin.", tagline_en:"Luxury without the bankruptcy.", vars:["--caramel","--sunset","--espresso","--card","--cream","--border"]},
  {slug:"pumpkin-spice", name:"Pumpkin Spice", icon:"svg-pumpkin", group:"coffee", desc:"Labu rempah earthy", tagline_id:"Vibes autumn, minus daun gugur.", tagline_en:"Autumn vibes, no fallen leaves.", vars:["--caramel","--sunset","--espresso","--card","--cream","--border"]},
  {slug:"midnight-roast", name:"Midnight Roast", icon:"fa-star", group:"coffee", desc:"Sangrai tengah malam", tagline_id:"Jam 2 pagi? Tetap kece.", tagline_en:"2 AM? Still slaying.", vars:["--caramel","--sunset","--espresso","--card","--cream","--border"]},
  // 10 Soft Dark (dark terang)
  {slug:"sunset-breeze", name:"Sunset Breeze", icon:"fa-sun", group:"soft", desc:"Senja orange lembut", tagline_id:"Ademnya nyeruput senja.", tagline_en:"Breathe in the sunset.", vars:["--caramel","--sunset","--espresso","--card","--cream","--border"]},
  {slug:"ocean-mist", name:"Ocean Mist", icon:"fa-water", group:"soft", desc:"Laut tenang biru", tagline_id:"Tenang kayak laut, bukan deadline.", tagline_en:"Calm like the ocean, not like deadlines.", vars:["--caramel","--sunset","--espresso","--card","--cream","--border"]},
  {slug:"forest-dew", name:"Forest Dew", icon:"fa-tree", group:"soft", desc:"Hutan hijau segar", tagline_id:"Segarnya kayak pagi di hutan.", tagline_en:"Fresh like a forest morning.", vars:["--caramel","--sunset","--espresso","--card","--cream","--border"]},
  {slug:"lavender-dream", name:"Lavender Dream", icon:"fa-spa", group:"soft", desc:"Lavender ungu dreamy", tagline_id:"Mimpi manis, tanpa ngorbanin kontras.", tagline_en:"Sweet dreams, full contrast.", vars:["--caramel","--sunset","--espresso","--card","--cream","--border"]},
  {slug:"peachy-sunset", name:"Peachy Sunset", icon:"fa-apple-whole", group:"soft", desc:"Persik hangat", tagline_id:"Manisnya nggak palsu.", tagline_en:"Sweet, not fake.", vars:["--caramel","--sunset","--espresso","--card","--cream","--border"]},
  {slug:"cherry-blossom", name:"Cherry Blossom", icon:"fa-fan", group:"soft", desc:"Sakura pink", tagline_id:"Romantis, tapi buat IDE.", tagline_en:"Romantic, but for your IDE.", vars:["--caramel","--sunset","--espresso","--card","--cream","--border"]},
  {slug:"mint-fresh", name:"Mint Fresh", icon:"fa-feather", group:"soft", desc:"Mint menyegarkan", tagline_id:"Napas kode jadi segar.", tagline_en:"Your code breathes fresh.", vars:["--caramel","--sunset","--espresso","--card","--cream","--border"]},
  {slug:"golden-hour", name:"Golden Hour", icon:"fa-crown", group:"soft", desc:"Emas senja", tagline_id:"Waktunya bersinar, bro.", tagline_en:"Time to shine, bro.", vars:["--caramel","--sunset","--espresso","--card","--cream","--border"]},
  {slug:"sky-blue", name:"Sky Blue", icon:"fa-cloud", group:"soft", desc:"Langit biru cerah", tagline_id:"Langit biru, hati tenang.", tagline_en:"Blue sky, calm heart.", vars:["--caramel","--sunset","--espresso","--card","--cream","--border"]},
  {slug:"rose-gold", name:"Rose Gold", icon:"fa-heart", group:"soft", desc:"Mawar emas lembut", tagline_id:"Elegant, nggak norak.", tagline_en:"Elegant, never tacky.", vars:["--caramel","--sunset","--espresso","--card","--cream","--border"]},
  // === TEMA EVENT ===
  {slug:"golden-eid", name:"Golden Eid", icon:"fa-diamond", group:"event", desc:"Emas hari raya", tagline_id:"Berkah & kehangatan", tagline_en:"Blessings & warmth", accent:"#2E8B57", vars:["--lebaran-1","--lebaran-2","--lebaran-3","--lebaran-4","--lebaran-5","--lebaran-6"]},
  {slug:"snowy-christmas", name:"Snowy Christmas", icon:"fa-snowflake", group:"event", desc:"Salju merah putih", tagline_id:"Dingin luar, hangat dalam", tagline_en:"Cold outside, warm inside", accent:"#4FA8E0", vars:["--natal-1","--natal-2","--natal-3","--natal-4","--natal-5","--natal-6"]},
  {slug:"independence-day", name:"Independence Day", icon:"fa-flag", group:"event", desc:"Merah putih bersemi", tagline_id:"Merah putih bersemi", tagline_en:"Red & white blooming", accent:"#E60012", vars:["--kemerdekaan-1","--kemerdekaan-2","--kemerdekaan-3","--kemerdekaan-4","--kemerdekaan-5","--kemerdekaan-6"]},
];

// Konfigurasi grup (extensible)
const GROUPS = [
  {key:"coffee", label_id:"10 Tema Coffee (Dark Pekat)", label_en:"10 Coffee Themes (Deep Dark)", sub_id:"Nuansa kopi klasik, mode gelap tetap dalam — tenang di mata, berani di warna.", sub_en:"Classic coffee vibes, dark mode stays deep — calm to eyes, bold in color.", icon:"fa-mug-hot", accent:"var(--caramel)"},
  {key:"soft",   label_id:"10 Tema Soft Dark (Dark Lebah Terang)", label_en:"10 Soft Dark Themes (Lighter Dark)", sub_id:"Mode gelap lebih terang & nyaman di mata untuk kerja malam panjang.", sub_en:"Lighter, eye-friendly dark mode for those long night sessions.", icon:"fa-cloud-sun", accent:"var(--sunset)"},
  {key:"event",  label_id:"Tema Event Khusus", label_en:"Special Event Themes", sub_id:"Koleksi tema musim & perayaan — pas buat moment spesial, ubah suasana sekali klik.", sub_en:"Seasonal & celebration themes — perfect for special moments, one click to shift the mood.", icon:"fa-calendar-star", accent:"var(--sunset-2)"}
];
